# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=15)),
                ('address', models.CharField(blank=15, max_length=50)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
